#!/usr/bin/env bash
# Fetch Anthropic's document skills (docx/pdf/pptx/xlsx) for LOCAL use.
# These are license: Proprietary (see each LICENSE.txt) — they must NOT be
# committed or republished; vendor/anthropic/ is gitignored.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASE="https://raw.githubusercontent.com/anthropics/skills/main/skills"
FILES="
docx/LICENSE.txt
docx/SKILL.md
docx/scripts/__init__.py
docx/scripts/accept_changes.py
docx/scripts/comment.py
docx/scripts/office/helpers/__init__.py
docx/scripts/office/helpers/merge_runs.py
docx/scripts/office/helpers/simplify_redlines.py
docx/scripts/office/pack.py
docx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-chart.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-chartDrawing.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-diagram.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-lockedCanvas.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-main.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-picture.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-spreadsheetDrawing.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-wordprocessingDrawing.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/pml.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-additionalCharacteristics.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-bibliography.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-commonSimpleTypes.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-customXmlDataProperties.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-customXmlSchemaProperties.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesCustom.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesExtended.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesVariantTypes.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-math.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-relationshipReference.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/sml.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-main.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-officeDrawing.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-presentationDrawing.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-spreadsheetDrawing.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-wordprocessingDrawing.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/wml.xsd
docx/scripts/office/schemas/ISO-IEC29500-4_2016/xml.xsd
docx/scripts/office/schemas/ecma/fouth-edition/opc-contentTypes.xsd
docx/scripts/office/schemas/ecma/fouth-edition/opc-coreProperties.xsd
docx/scripts/office/schemas/ecma/fouth-edition/opc-digSig.xsd
docx/scripts/office/schemas/ecma/fouth-edition/opc-relationships.xsd
docx/scripts/office/schemas/mce/mc.xsd
docx/scripts/office/schemas/microsoft/wml-2010.xsd
docx/scripts/office/schemas/microsoft/wml-2012.xsd
docx/scripts/office/schemas/microsoft/wml-2018.xsd
docx/scripts/office/schemas/microsoft/wml-cex-2018.xsd
docx/scripts/office/schemas/microsoft/wml-cid-2016.xsd
docx/scripts/office/schemas/microsoft/wml-sdtdatahash-2020.xsd
docx/scripts/office/schemas/microsoft/wml-symex-2015.xsd
docx/scripts/office/soffice.py
docx/scripts/office/unpack.py
docx/scripts/office/validate.py
docx/scripts/office/validators/__init__.py
docx/scripts/office/validators/base.py
docx/scripts/office/validators/docx.py
docx/scripts/office/validators/pptx.py
docx/scripts/office/validators/redlining.py
docx/scripts/templates/comments.xml
docx/scripts/templates/commentsExtended.xml
docx/scripts/templates/commentsExtensible.xml
docx/scripts/templates/commentsIds.xml
docx/scripts/templates/people.xml
pdf/FORMS.md
pdf/LICENSE.txt
pdf/REFERENCE.md
pdf/SKILL.md
pdf/scripts/check_bounding_boxes.py
pdf/scripts/check_fillable_fields.py
pdf/scripts/convert_pdf_to_images.py
pdf/scripts/create_validation_image.py
pdf/scripts/extract_form_field_info.py
pdf/scripts/extract_form_structure.py
pdf/scripts/fill_fillable_fields.py
pdf/scripts/fill_pdf_form_with_annotations.py
pptx/LICENSE.txt
pptx/SKILL.md
pptx/editing.md
pptx/pptxgenjs.md
pptx/scripts/__init__.py
pptx/scripts/add_slide.py
pptx/scripts/clean.py
pptx/scripts/office/helpers/__init__.py
pptx/scripts/office/helpers/merge_runs.py
pptx/scripts/office/helpers/simplify_redlines.py
pptx/scripts/office/pack.py
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-chart.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-chartDrawing.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-diagram.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-lockedCanvas.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-main.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-picture.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-spreadsheetDrawing.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-wordprocessingDrawing.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/pml.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-additionalCharacteristics.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-bibliography.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-commonSimpleTypes.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-customXmlDataProperties.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-customXmlSchemaProperties.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesCustom.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesExtended.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesVariantTypes.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-math.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-relationshipReference.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/sml.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-main.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-officeDrawing.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-presentationDrawing.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-spreadsheetDrawing.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-wordprocessingDrawing.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/wml.xsd
pptx/scripts/office/schemas/ISO-IEC29500-4_2016/xml.xsd
pptx/scripts/office/schemas/ecma/fouth-edition/opc-contentTypes.xsd
pptx/scripts/office/schemas/ecma/fouth-edition/opc-coreProperties.xsd
pptx/scripts/office/schemas/ecma/fouth-edition/opc-digSig.xsd
pptx/scripts/office/schemas/ecma/fouth-edition/opc-relationships.xsd
pptx/scripts/office/schemas/mce/mc.xsd
pptx/scripts/office/schemas/microsoft/wml-2010.xsd
pptx/scripts/office/schemas/microsoft/wml-2012.xsd
pptx/scripts/office/schemas/microsoft/wml-2018.xsd
pptx/scripts/office/schemas/microsoft/wml-cex-2018.xsd
pptx/scripts/office/schemas/microsoft/wml-cid-2016.xsd
pptx/scripts/office/schemas/microsoft/wml-sdtdatahash-2020.xsd
pptx/scripts/office/schemas/microsoft/wml-symex-2015.xsd
pptx/scripts/office/soffice.py
pptx/scripts/office/unpack.py
pptx/scripts/office/validate.py
pptx/scripts/office/validators/__init__.py
pptx/scripts/office/validators/base.py
pptx/scripts/office/validators/docx.py
pptx/scripts/office/validators/pptx.py
pptx/scripts/office/validators/redlining.py
pptx/scripts/rezip.py
pptx/scripts/thumbnail.py
xlsx/LICENSE.txt
xlsx/SKILL.md
xlsx/scripts/office/helpers/__init__.py
xlsx/scripts/office/helpers/merge_runs.py
xlsx/scripts/office/helpers/simplify_redlines.py
xlsx/scripts/office/pack.py
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-chart.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-chartDrawing.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-diagram.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-lockedCanvas.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-main.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-picture.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-spreadsheetDrawing.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/dml-wordprocessingDrawing.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/pml.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-additionalCharacteristics.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-bibliography.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-commonSimpleTypes.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-customXmlDataProperties.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-customXmlSchemaProperties.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesCustom.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesExtended.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-documentPropertiesVariantTypes.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-math.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/shared-relationshipReference.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/sml.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-main.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-officeDrawing.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-presentationDrawing.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-spreadsheetDrawing.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/vml-wordprocessingDrawing.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/wml.xsd
xlsx/scripts/office/schemas/ISO-IEC29500-4_2016/xml.xsd
xlsx/scripts/office/schemas/ecma/fouth-edition/opc-contentTypes.xsd
xlsx/scripts/office/schemas/ecma/fouth-edition/opc-coreProperties.xsd
xlsx/scripts/office/schemas/ecma/fouth-edition/opc-digSig.xsd
xlsx/scripts/office/schemas/ecma/fouth-edition/opc-relationships.xsd
xlsx/scripts/office/schemas/mce/mc.xsd
xlsx/scripts/office/schemas/microsoft/wml-2010.xsd
xlsx/scripts/office/schemas/microsoft/wml-2012.xsd
xlsx/scripts/office/schemas/microsoft/wml-2018.xsd
xlsx/scripts/office/schemas/microsoft/wml-cex-2018.xsd
xlsx/scripts/office/schemas/microsoft/wml-cid-2016.xsd
xlsx/scripts/office/schemas/microsoft/wml-sdtdatahash-2020.xsd
xlsx/scripts/office/schemas/microsoft/wml-symex-2015.xsd
xlsx/scripts/office/soffice.py
xlsx/scripts/office/unpack.py
xlsx/scripts/office/validate.py
xlsx/scripts/office/validators/__init__.py
xlsx/scripts/office/validators/base.py
xlsx/scripts/office/validators/docx.py
xlsx/scripts/office/validators/pptx.py
xlsx/scripts/office/validators/redlining.py
xlsx/scripts/recalc.py
"
for f in $FILES; do
  dest="$ROOT/vendor/anthropic/$f"
  mkdir -p "$(dirname "$dest")"
  curl -fsS "$BASE/$f" -o "$dest" && echo "fetched $f" || echo "MISS $f (upstream layout drift)"
done
echo "Done. Local use only — see LICENSE.txt in each skill dir."
