#!/usr/bin/env python3
"""Regenerate the skill catalog in skills/CLAUDE.md between INDEX markers.
Also prints the standing metadata cost (name+description token estimate).
Idempotent; run after adding/renaming skills. Exit 2 if markers missing."""
import re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
FM = re.compile(r"\A---\s*\n(.*?)\n---", re.S)
BEGIN, END = "<!-- INDEX:BEGIN (generated by tools/gen-index.py) -->", "<!-- INDEX:END -->"

def first_sentence(desc: str) -> str:
    s = desc.split(". ")[0].strip()
    return (s[:110] + "…") if len(s) > 112 else s

def desc_of(p: Path):
    m = FM.match(p.read_text(encoding="utf-8", errors="replace"))
    if not m: return None
    lines, cap, out = m.group(1).splitlines(), False, []
    for line in lines:
        if line.startswith("description:"):
            out.append(line.split(":", 1)[1].strip()); cap = True
        elif cap and line.startswith((" ", "\t")): out.append(line.strip())
        elif cap: break
    return " ".join(out)

def main() -> int:
    rows, total_chars = [], 0
    for d in sorted((ROOT / "skills").iterdir()):
        f = d / "SKILL.md"
        if not (d.is_dir() and f.exists()): continue
        desc = desc_of(f) or ""
        total_chars += len(d.name) + len(desc)
        rows.append(f"- `{d.name}` — {first_sentence(desc)}")
    guide = ROOT / "skills" / "CLAUDE.md"
    t = guide.read_text()
    if BEGIN not in t or END not in t:
        print("markers missing in skills/CLAUDE.md", file=sys.stderr); return 2
    block = BEGIN + "\n" + "\n".join(rows) + "\n" + END
    t = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, t, flags=re.S)
    guide.write_text(t)
    print(f"index: {len(rows)} skills; standing metadata ≈ {total_chars // 4} tokens (chars/4)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
