#!/usr/bin/env python3
"""Regenerate the artifact catalogs between INDEX markers, grouped by `flow:`.

Targets: skills/CLAUDE.md (skills), commands/CLAUDE.md (commands),
agents/CLAUDE.md (agents). Also prints the standing metadata cost
(name+description token estimate) per catalog.
Idempotent; run after adding/renaming anything. Exit 2 if markers missing."""
import re
import sys
from pathlib import Path

# Emit UTF-8 regardless of the platform default codec (e.g. Windows cp1252),
# so this runs clean in plain PowerShell without PYTHONUTF8=1.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
FM = re.compile(r"\A---\s*\n(.*?)\n---", re.S)
BEGIN, END = "<!-- INDEX:BEGIN (generated by tools/gen-index.py) -->", "<!-- INDEX:END -->"
# Presentation order — matches the FLOWS vocabulary in validate.py.
FLOW_ORDER = ("plan", "execute", "review", "debug", "lookup", "deliver", "session", "util", "meta", "career")
FLOW_LABELS = {
    "plan": "Plan — shape the work before code",
    "execute": "Execute — build it (loop or TDD)",
    "review": "Review — pre-ship checks",
    "debug": "Debug — find and fix root cause",
    "lookup": "Lookup — find code/data/facts mid-task",
    "deliver": "Deliver — commits, PRs, docs, artifacts",
    "session": "Session — context, cost, handoffs",
    "util": "Util — library how-tos for scripts",
    "meta": "Meta — build the toolbox itself",
    "career": "Career — interview and resume practice",
}


def first_sentence(desc: str) -> str:
    s = desc.split(". ")[0].strip()
    return (s[:110] + "…") if len(s) > 112 else s


def fields_of(p: Path):
    m = FM.match(p.read_text(encoding="utf-8", errors="replace"))
    if not m:
        return None
    lines, cap, desc = m.group(1).splitlines(), False, []
    flow = domain = ""
    for line in lines:
        if line.startswith("description:"):
            desc.append(line.split(":", 1)[1].strip())
            cap = True
        elif cap and line.startswith((" ", "\t")):
            desc.append(line.strip())
        else:
            cap = False
            if line.startswith("flow:"):
                flow = line.split(":", 1)[1].strip()
            elif line.startswith("domain:"):
                domain = line.split(":", 1)[1].strip()
    return " ".join(desc), flow, domain


def entries(kind: str):
    d = ROOT / kind
    out = []
    if kind == "skills":
        for sub in sorted(d.iterdir()):
            f = sub / "SKILL.md"
            if sub.is_dir() and f.exists():
                out.append((sub.name, f))
    else:
        for f in sorted(d.glob("*.md")):
            if f.name != "CLAUDE.md":
                out.append((f.stem, f))
    return out


def render(kind: str) -> tuple[str, int, int]:
    grouped: dict[str, list[tuple[str, str]]] = {}
    total_chars = count = 0
    for name, f in entries(kind):
        got = fields_of(f)
        if got is None:
            continue
        desc, flow, domain = got
        total_chars += len(name) + len(desc)
        count += 1
        grouped.setdefault(flow or "unassigned", []).append(
            (domain or "~", f"- `{name}` ·{domain}· — {first_sentence(desc)}")
        )
    parts = []
    for flow in (*FLOW_ORDER, "unassigned"):
        if flow in grouped:
            parts.append(f"**{FLOW_LABELS.get(flow, flow)}**")
            parts.extend(line for _, line in sorted(grouped[flow]))
            parts.append("")
    return "\n".join(parts).rstrip(), count, total_chars


def main() -> int:
    rc = 0
    for kind in ("skills", "commands", "agents"):
        guide = ROOT / kind / "CLAUDE.md"
        t = guide.read_text(encoding="utf-8")
        if BEGIN not in t or END not in t:
            print(f"markers missing in {kind}/CLAUDE.md", file=sys.stderr)
            rc = 2
            continue
        body, count, chars = render(kind)
        block = BEGIN + "\n" + body + "\n" + END
        t = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, t, flags=re.S)
        guide.write_text(t, encoding="utf-8", newline="\n")
        print(f"index[{kind}]: {count} entries; standing metadata ~ {chars // 4} tokens (chars/4)")
    return rc


if __name__ == "__main__":
    sys.exit(main())
